[assembly: global::System.Reflection.AssemblyProduct("Microsoft® .NET Framework")]
[assembly: global::System.CLSCompliant(false)]
[assembly: global::System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: global::System.Reflection.AssemblyDescription("System.Runtime.CompilerServices.Unsafe")]
[assembly: global::System.Reflection.AssemblyFileVersion("6.0.21.52210")]
[assembly: global::System.Reflection.AssemblyInformationalVersion("6.0.0")]
[assembly: global::System.Reflection.AssemblyTitle("System.Runtime.CompilerServices.Unsafe")]
[assembly: global::System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: global::System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
[assembly: global::System.Reflection.AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: global::System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: global::System.Reflection.AssemblyVersion("6.0.0.0")]
