namespace UnityEngine.AdaptivePerformance
{
	public delegate void PerformanceBottleneckChangeHandler(global::UnityEngine.AdaptivePerformance.PerformanceBottleneckChangeEventArgs bottleneckEventArgs);
}
