[assembly: global::System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: global::System.Reflection.AssemblyMetadata("PreferInbox", "True")]
[assembly: global::System.Reflection.AssemblyDefaultAlias("System.IO.Hashing")]
[assembly: global::System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: global::System.CLSCompliant(true)]
[assembly: global::System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
[assembly: global::System.Runtime.InteropServices.DefaultDllImportSearchPaths(global::System.Runtime.InteropServices.DllImportSearchPath.System32 | global::System.Runtime.InteropServices.DllImportSearchPath.AssemblyDirectory)]
[assembly: global::System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: global::System.Reflection.AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: global::System.Reflection.AssemblyDescription("Provides non-cryptographic hash algorithms, such as CRC-32.\r\n\r\nCommonly Used Types:\r\nSystem.IO.Hashing.Crc32\r\nSystem.IO.Hashing.XxHash32")]
[assembly: global::System.Reflection.AssemblyFileVersion("9.0.24.52809")]
[assembly: global::System.Reflection.AssemblyInformationalVersion("9.0.0+9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3")]
[assembly: global::System.Reflection.AssemblyProduct("Microsoft® .NET")]
[assembly: global::System.Reflection.AssemblyTitle("System.IO.Hashing")]
[assembly: global::System.Reflection.AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: global::System.Reflection.AssemblyVersion("9.0.0.0")]
[module: global::System.Runtime.CompilerServices.NullablePublicOnly(false)]
