[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.UI")]
[assembly: global::System.Reflection.AssemblyTitle("guisystem")]
[assembly: global::System.Reflection.AssemblyDescription("")]
[assembly: global::System.Reflection.AssemblyConfiguration("")]
[assembly: global::System.Reflection.AssemblyCompany("Microsoft")]
[assembly: global::System.Reflection.AssemblyProduct("guisystem")]
[assembly: global::System.Reflection.AssemblyCopyright("Copyright © Microsoft 2013")]
[assembly: global::System.Reflection.AssemblyTrademark("")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.UI.Tests")]
[assembly: global::System.Runtime.InteropServices.ComVisible(false)]
[assembly: global::System.Runtime.InteropServices.Guid("d4f464c7-9b15-460d-b4bc-2cacd1c1df73")]
[assembly: global::System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyVersion("1.0.0.0")]
