[assembly: global::System.Security.AllowPartiallyTrustedCallers]
[assembly: global::System.Reflection.AssemblyDelaySign(true)]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Newtonsoft.Json.Schema")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Newtonsoft.Json.Tests")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Newtonsoft.Json.Dynamic")]
[assembly: global::System.Reflection.AssemblyTrademark("")]
[assembly: global::System.Runtime.InteropServices.ComVisible(false)]
[assembly: global::System.Runtime.InteropServices.Guid("9ca358aa-317b-4925-8ada-4a29e943a363")]
[assembly: global::System.CLSCompliant(true)]
[assembly: global::System.Reflection.AssemblyCompany("Newtonsoft")]
[assembly: global::System.Reflection.AssemblyConfiguration("UnityAOT")]
[assembly: global::System.Reflection.AssemblyCopyright("Copyright © James Newton-King 2008")]
[assembly: global::System.Reflection.AssemblyDescription("Json.NET is a popular high-performance JSON framework for .NET")]
[assembly: global::System.Reflection.AssemblyFileVersion("13.0.2")]
[assembly: global::System.Reflection.AssemblyInformationalVersion("13.0.2+cf0a246981c33ae00121dfe58b850aefeac1aac0")]
[assembly: global::System.Reflection.AssemblyProduct("Json.NET")]
[assembly: global::System.Reflection.AssemblyTitle("Json.NET .NET Standard 2.0")]
[assembly: global::System.Reflection.AssemblyMetadata("RepositoryUrl", "https://github.com/sousapedro/Newtonsoft.Json-for-Unity.git")]
[assembly: global::System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: global::System.Reflection.AssemblyVersion("13.0.0.0")]
