[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.Core.Editor")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.Flow.Editor")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.Flow")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.State.Editor")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.State")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.SettingsProvider.Editor")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.Tests.Editor")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.VisualScripting.Tests")]
[assembly: global::Unity.VisualScripting.RenamedNamespace("Bolt", "Unity.VisualScripting")]
[assembly: global::Unity.VisualScripting.RenamedNamespace("Ludiq", "Unity.VisualScripting")]
[assembly: global::System.Reflection.AssemblyVersion("0.0.0.0")]
