#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using RenPy.Unity;

namespace RenPy.EditorTools
{
    /// <summary>
    /// Writes the file manifest a Ren'Py game needs on Android.
    ///
    /// StreamingAssets is packed inside the APK there, so the runtime cannot list a
    /// directory. This records every file up front so the player can copy them out
    /// on first launch.
    /// </summary>
    public static class RenPyManifestGenerator
    {
        const string MenuPath = "Tools/Ren'Py/Generate Manifest for StreamingAssets Games";

        [MenuItem(MenuPath)]
        public static void GenerateAll()
        {
            string streamingAssets = Application.streamingAssetsPath;

            if (!Directory.Exists(streamingAssets))
            {
                EditorUtility.DisplayDialog("Ren'Py",
                    "There is no StreamingAssets folder yet.\n\nCreate Assets/StreamingAssets and put your unzipped Ren'Py game inside it.",
                    "OK");
                return;
            }

            var generated = new List<string>();

            foreach (var candidate in FindGameRoots(streamingAssets))
            {
                int count = WriteManifest(candidate);
                generated.Add(Relative(streamingAssets, candidate) + "  (" + count + " files)");
            }

            AssetDatabase.Refresh();

            if (generated.Count == 0)
            {
                EditorUtility.DisplayDialog("Ren'Py",
                    "No Ren'Py games found under StreamingAssets.\n\n" +
                    "A game is a folder containing a 'game' subfolder with .rpyc files in it.",
                    "OK");
                return;
            }

            EditorUtility.DisplayDialog("Ren'Py",
                "Wrote " + RenPyFileSystem.ManifestName + " for:\n\n" + string.Join("\n", generated.ToArray()),
                "OK");
        }

        /// <summary>Finds folders under StreamingAssets that contain a Ren'Py `game` directory.</summary>
        static IEnumerable<string> FindGameRoots(string streamingAssets)
        {
            var pending = new Queue<string>();
            pending.Enqueue(streamingAssets);

            while (pending.Count > 0)
            {
                string dir = pending.Dequeue();

                if (Directory.Exists(Path.Combine(dir, "game")))
                {
                    yield return dir;
                    continue;   // do not descend into a game we already found
                }

                foreach (var child in Directory.GetDirectories(dir))
                {
                    string name = Path.GetFileName(child);
                    if (name.StartsWith(".", StringComparison.Ordinal)) continue;
                    pending.Enqueue(child);
                }
            }
        }

        static int WriteManifest(string gameRoot)
        {
            var lines = new List<string>();
            int prefix = gameRoot.Length + 1;

            foreach (var path in Directory.EnumerateFiles(gameRoot, "*", SearchOption.AllDirectories))
            {
                string file = Path.GetFileName(path);

                // Unity's own sidecars and our previous manifest are not game data.
                if (file.EndsWith(".meta", StringComparison.OrdinalIgnoreCase)) continue;
                if (file == RenPyFileSystem.ManifestName) continue;
                if (file == ".DS_Store" || file == "Thumbs.db") continue;

                lines.Add(path.Substring(prefix).Replace('\\', '/'));
            }

            lines.Sort(StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("# Generated by Tools > Ren'Py > Generate Manifest.");
            sb.AppendLine("# Lists every game file so Android can install them out of the APK.");
            foreach (var line in lines) sb.AppendLine(line);

            File.WriteAllText(Path.Combine(gameRoot, RenPyFileSystem.ManifestName), sb.ToString());
            return lines.Count;
        }

        static string Relative(string root, string path)
        {
            return path.Length > root.Length ? path.Substring(root.Length + 1) : Path.GetFileName(path);
        }
    }
}
#endif
