[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("DOTweenEditor")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("DOTween43")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("DOTween46")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("DOTween50")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("DOTweenPro")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("DOTweenProEditor")]
[assembly: global::System.Reflection.AssemblyTitle("DOTween")]
[assembly: global::System.Reflection.AssemblyDescription("")]
[assembly: global::System.Reflection.AssemblyConfiguration("")]
[assembly: global::System.Reflection.AssemblyCompany("Demigiant")]
[assembly: global::System.Reflection.AssemblyProduct("DOTween")]
[assembly: global::System.Reflection.AssemblyCopyright("Copyright © Daniele Giardini, 2014")]
[assembly: global::System.Reflection.AssemblyTrademark("")]
[assembly: global::System.Runtime.InteropServices.ComVisible(false)]
[assembly: global::System.Runtime.InteropServices.Guid("807e068c-2a0e-4c81-a303-4b4fd3924511")]
[assembly: global::System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyVersion("1.0.0.0")]
