namespace Unity.Services.Multiplayer
{
	public enum SessionError
	{
		None = 0,
		Unknown = 1,
		NotAuthorized = 2,
		NotInLobby = 3,
		LobbyAlreadyExists = 4,
		SessionTypeAlreadyExists = 5,
		SessionNotFound = 6,
		SessionDeleted = 7,
		AllocationAlreadyExists = 8,
		AllocationNotFound = 9,
		Forbidden = 10,
		RateLimitExceeded = 11,
		InvalidParameter = 12,
		InvalidMatchmakerTicket = 13,
		InvalidMatchmakerAssignment = 14,
		InvalidMatchmakerState = 15,
		InvalidMatchmakerResults = 16,
		InvalidNetworkConfig = 17,
		InvalidSessionMetadata = 18,
		InvalidPlatformOperation = 19,
		InvalidOperation = 20,
		MatchmakerAssignmentFailed = 21,
		MatchmakerAssignmentTimeout = 22,
		MatchmakerCancelled = 23,
		MissingAssembly = 24,
		MultiplayServerError = 25,
		NetworkManagerNotInitialized = 26,
		NetworkManagerStartFailed = 27,
		NetworkSetupFailed = 28,
		TranportComponentMissing = 29,
		TransportComponentMissing = 29,
		TransportInvalid = 30,
		AlreadySubscribedToLobby = 31,
		InvalidCreateSessionOptions = 32,
		InvalidBackfillTicket = 33,
		InvalidLocalMatchProperties = 34,
		InvalidPlayerTeam = 35,
		PlayerMissingTeamProperties = 36,
		QoSMeasurementFailed = 37,
		MigrationDataRequestTimeout = 38,
		MatchmakerModuleMissing = 39,
		InvalidMatchmakerOptions = 40,
		OutOfSyncSession = 41,
		InvalidSessionIdentifier = 42,
		InvalidPlayerName = 43,
		PlayerNameSynchronizationFailed = 44,
		SessionConflict = 45,
		InvalidBackfillTicketOptions = 46
	}
}
