[assembly: global::System.Reflection.AssemblyTitle("UnityEngine.Timeline")]
[assembly: global::System.Reflection.AssemblyDescription("Unity Timeline")]
[assembly: global::System.Reflection.AssemblyConfiguration("")]
[assembly: global::System.Reflection.AssemblyCompany("Unity Technologies")]
[assembly: global::System.Reflection.AssemblyProduct("UnityEngine.Timeline")]
[assembly: global::System.Reflection.AssemblyCopyright("Copyright \ufffd 2016")]
[assembly: global::System.Reflection.AssemblyTrademark("")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Timeline.Editor")]
[assembly: global::System.Runtime.InteropServices.ComVisible(false)]
[assembly: global::System.Runtime.InteropServices.Guid("6A10B290-9283-487F-913B-00D94CD3FAF5")]
[assembly: global::System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-testable")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Assembly-CSharp-Editor-testable")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Timeline.EditorTests")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Timeline.Tests")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Timeline.Tests.Common")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Timeline.Tests.Performance")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Timeline.Tests.Performance.Editor")]
[assembly: global::System.Reflection.AssemblyVersion("1.0.0.0")]
