[assembly: global::System.Reflection.AssemblyKeyName("")]
[assembly: global::System.Reflection.AssemblyDelaySign(false)]
[assembly: global::System.Reflection.AssemblyConfiguration("")]
[assembly: global::System.Reflection.AssemblyTitle("ANTLR3.Runtime.NET")]
[assembly: global::System.Reflection.AssemblyDescription("ANTLR3 C# Runtime for .NET")]
[assembly: global::System.Reflection.AssemblyCompany("")]
[assembly: global::System.Reflection.AssemblyProduct("")]
[assembly: global::System.Reflection.AssemblyCopyright("Copyright (c) 2005-2007 Kunle Odutola, 2007-2009 Johannes Luber")]
[assembly: global::System.Reflection.AssemblyTrademark("")]
[assembly: global::System.Security.AllowPartiallyTrustedCallers]
[assembly: global::System.Reflection.AssemblyVersion("3.1.3.22795")]
