[assembly: global::System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: global::System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Burst")]
[assembly: global::System.Reflection.AssemblyFileVersion("4.0.0.0")]
[assembly: global::System.Reflection.AssemblyInformationalVersion("4.0.0.0")]
[assembly: global::System.Reflection.AssemblyTitle("Unity.Burst.Unsafe")]
[assembly: global::System.Reflection.AssemblyDescription("System.Runtime.CompilerServices.Unsafe")]
[assembly: global::System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: global::System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: global::System.Reflection.AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: global::System.Reflection.AssemblyProduct("Microsoft® .NET Framework")]
[assembly: global::System.CLSCompliant(false)]
[assembly: global::System.Reflection.AssemblyVersion("4.0.5.0")]
